---
apiVersion: v1
kind: Pod
metadata:
  name: orange-app-cka10-trb
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: orange-app-cka10-trb-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: radial/busyboxplus:curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -sSf http://orange-app-cka10-trb-service:80 || exit 1
          restartPolicy: OnFailure