---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: green-sa-cka22-arch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: green-role-cka22-arch
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: green-role-binding-cka22-arch
subjects:
- kind: ServiceAccount
  name: green-sa-cka22-arch # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: green-role-cka22-arch
  apiGroup: rbac.authorization.k8s.io
